### ISSUE TITLE
Could you share the dataset of the Superliga Argentina competition?

### ISSUE THREAD

**Issue by ferraresso** [mesosbrodleto/playerank#1]
Hi, first of all, thanks for sharing your gut and development. I'm Argentine and that part of the dataset would be very useful to me

**Comment by jonpappalord** [comment]
Hi @ferraresso, unfortunately, we are not allowed to share the data about Superliga Argentina competition. We recently released some European competitions, you can use them: https://www.nature.com/articles/s41597-019-0247-7
